l_square = input ('What is the length of the square? ')
square_a = str(float(int(l_square)**2))
print ('The area of the square is : ' + square_a )
l_rec = input ('What is the length of rectangle? ')
w_rec = input ('What is the width of rectangle? ')
rec_a = str(float(int(l_rec)*int(w_rec)))
print ('The area os the rectangle is : ' + rec_a)
r_circle = input ('What is the radius of the circle? ')
circle_a = str(float(int(r_circle)**2*3.14))
print ('The area of the circle is : ' + circle_a)