child_m = input("What is the price of a child's meal? ")
adult_m = input("What is the price of an adult's meal? ")
n_child = input("How many children are there? ")
n_adult = input("How many adults are there? ")
sales_tax_rate = input("What is the sales tax rate? ")
print()
subtotal = float(child_m)*float(n_child)+float(adult_m)*float(n_adult)
print(f'Subtotal: ${subtotal:.2f}')
sales_tax = float(subtotal)*float(sales_tax_rate)/100
print(f'Sales Tax: ${sales_tax:.2f}')
total = float(sales_tax)+float(subtotal)
print(f'Total: ${total:.2f}')
print()
payment = input('What is the payment amount? ')
change = float(payment)-float(total)
print(f'Change: ${change:.2f}')
