child_m = input("What is the price of a child's meal? ")
adult_m = input("What is the price of an adult's meal? ")
n_child = input("How many children are there? ")
n_adult = input("How many adults are there? ")
sales_tax_rate = input("What is the sales tax rate? ")
print()
subtotal = str(float(child_m)*float(n_child)+float(adult_m)*float(n_adult))
print('Subtotal: $' + subtotal)
sales_tax = str(float(subtotal)*float(sales_tax_rate)/100)
print('Sales Tax: ' + sales_tax)
total = str(float(sales_tax)+float(subtotal))
print('Total: $' + total)
print()
payment = input('What is the payment amount? ')
change = str(float(payment)-float(total))
print('Change: $' + (change).format)