print()
age=input('How old are you? ')
age_next_year=str(int(age)+1)
print('On your next birthday, you will be '+age_next_year+'.')
print()
carton=input('How many egg cartons do you have? ')
eggs=str(int(carton)*12)
print('You have '+eggs+' eggs.')
print()
cookies=input('How many cookies do you have? ')
people=input('How many people are there? ')
each_have=str(int(cookies)/int(people))
print('Each people may have '+each_have+' cookies.')


